image:
  file: .gitpod.Dockerfile
tasks:
  - init: cargo build
    command: cargo watch -x run
  - command: |
      bash scripts/gitpod.sh;
      gp ports await 3306 &&
      mysql -e "CREATE DATABASE iclip;";
      mysql < scripts/db.sql;

vscode:
  extensions:
    - rust-lang.rust-analyzer