ports:
  - port: 8000
    onOpen: open-browser
    visibility: public
    name: Server
  - port: 3306
    onOpen: ignore
    name: MySQL Database
  - port: 6379
    onOpen: ignore
    name: Redis

image:
  file: .gitpod.Dockerfile
tasks:
  - init: cargo build
    command: cargo watch -x run
  - command: |
      bash scripts/gitpod.sh;
      gp ports await 3306 &&
      mysql -e "CREATE DATABASE iclip;";
      mysql < scripts/db.sql;
  - name: Redis
    command: redis-server

vscode:
  extensions:
    - rust-lang.rust-analyzer